### ISSUE TITLE
Donde puedo encontrar los archivos es_modelYahooQA.model ?

### ISSUE THREAD

**Issue by nguaman** [beeva-nievesabalos/scripts#1]
Hola! como estas?

estaba revisando tus scripts y quería testearlos! pero no encuentro los archivos fuentes

https://github.com/beeva-nievesabalos/scripts/blob/master/yahoo-answers/yahoo-gensim.py

Sería posible que los subieras? 

Estoy recien iniciandome con word2vec y me costo encontrar ejemplos en español, espero que me puedas ayudar!

Saludos!

**Comment by beeva-nievesabalos** [comment]
Pues ese archivo es un preprocesado del original, que no puedo subir por los "términos legales" de Yahoo, pero podrás encontrarlos aquí: https://webscope.sandbox.yahoo.com/#datasets 

Han cambiado la página desde que entré hace 2 años, pero deberían estar ahí.

Efectivamente, hay pocos datasets públicos en español.

Espero que te sirva.

Saludos!

**Comment by nguaman** [comment]
Muchas Gracias @beeva-nievesabalos ! 

Saludos!
